config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope "/blog" do
    resources :posts
  end
  get '/parties' => 'static_pages#home'
  get '/form' => 'static_pages#typeform'
  get '/admin' => 'admin#home'
 root 'static_pages#weddings'
 

end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :pathname, uniqueness: true
    def to_param
        pathname
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def home
    check_if_current_user_is_clancy
    @posts = Post.all
  end
  
  private
    def check_if_current_user_is_clancy
      if current_user.email.downcase != "clancy@cjyourdj.com"
        redirect_to "/"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def static_pages 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:[:show, :index]
  before_action :check_if_current_user_is_clancy, except:[:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show    
    # respond_to do |format|
    #   if @post.save
    #     format.html { redirect_to @post, notice: 'Post was successfully created.' }
    #     format.json { render :show, status: :created, location: @post.pathname }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.pathname = @post.title.scan(/\w|\s/).join('').downcase.truncate(20, omission:'').split(" ").join('-')

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post.pathname }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post =  Post.find_by(pathname: params[:id])
    end

    def check_if_current_user_is_clancy
      if current_user.email.downcase != "clancy@cjyourdj.com"
        redirect_to "/"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :subtitle, :author, :body, :pathname)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def typeform
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gfont(fonts)
        return "<link href='https://fonts.googleapis.com/css?family=#{fonts.join('|')}' rel='stylesheet'>"
    end
    def description
        return "At CJ's Mobile DJ, we are passionate about making music into memories."
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/home.html.haml
.container
	.row
		.col-sm-6.col-sm-offset-3
			.elevated-box
				%h1 Useful Links
				-if user_signed_in?
					=link_to('Logout', destroy_user_session_path, :method => :delete, class:"btn btn-primary")
				-else
					= link_to('Login', new_user_session_path, class:"btn btn-primary")
				=link_to "New Blog Post", new_post_path, class:"btn btn-primary"
				-(0..5).each do |a|
					%br
	.row
		-@posts.each do |post|
			.col-xs-12.col-md-6
				.elevated-box
					.h3= post.title
					.h3
					%small= post.subtitle
					%p= post.author
					%p.fr-view!=post.body.truncate_words(28)
					= link_to 'Show', post_path(post), class:"btn btn-primary"
					= link_to 'Edit', edit_post_path(post), class:"btn btn-primary"
					= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary"
					= link_to 'New Post', new_post_path, class:"btn btn-primary"

app/views/layouts/application.html.haml
%head
	%title CJ's Mobile DJ - Boise, Idaho | Weddings | Parties | Dances | Special Events
	%meta{name:"description", content:description}
	%meta{name:"keywords", content:"boise dj, boise wedding dj, idaho dj, best boise djs, idaho wedding dj, mccall wedding dj, sun valley wedding dj, boise event lighting, boise wedding lighting, boise dj, boise disc jockey, idaho disc jockey, boise event lighting"}
	-if action_name =~ /(new)|(edit)|(admin)/
		%meta{name:"robots", content:"noindex, nofollow"}

	-# = javascript_include_tag 'angular', 'data-turbolinks-track' => true 
	=favicon_link_tag 'record.png', rel: 'shortcut icon', type: 'image/png'
	-fonts = %w(Lusitana Open+Sans Roboto:900 Anton Chelsea+Market Montserrat)
	<meta name="viewport" content="width=device-width, initial-scale=1">
	!=gfont(fonts)
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= stylesheet_link_tag params[:controller]
	= csrf_meta_tags 

	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-61921012-5', 'auto');
	ga('send', 'pageview');

	</script>

	</head>

%body{"ng-app":"cj-mobile-dj", "ng-controller":"AnalyticsController as ac"}
	= yield 
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/canvas-confetti@0.0.3/dist/confetti.browser.min.js"></script>
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 

app/views/posts/_form.html.haml
.container-fluid.form-page
  .form-container
    =form_for(@post) do |f|
      -if @post.errors.any?
        .error#error_explanation
        .h2= pluralize(@post.errors.count, "error")
        .h2 prohibited this post from being saved:
        -@post.errors.full_messages.each do |msg|
          %li.h4=msg
      .row
        .form-field-container
          .field
            =f.label :title
            =f.text_area :title, class:"form-control simple-entry", required:'true'
          .field
            =f.label :subtitle
            =f.text_area :subtitle, class:"form-control simple-entry", required:'true'
          .field
            =f.label :author
            =f.text_area :author, class:"form-control simple-entry", required:'true'
          .field
            =f.label :pathname
            =f.text_field :pathname, class:"form-control simple-entry", required:'false'
      .row
        .col-xs-12
          .field
            =f.label :body
            =f.text_area :body, class:"form-control", id:"edit", value:"", style:"height:200%"
      .row
        .col-xs-12.col-md-4.col-md-offset-4
          .field
          =f.submit class:"btn btn-primary"
          
<script>

$(function() {
$('#edit').froalaEditor()
});
</script>

app/views/posts/_nav.html.haml
.row.background-5.bg
    .dark-row
        .container-fluid
            .row.nav-row
                .col-sm-1.col-xs-0
                .col-sm-5.col-xs-12.text-left
                    %a{href:"#{root_path}", "ng-click":"wc.action=false"}
                        .h1 
                            =image_tag "heart-logo-square.svg", fill:'pink', style:"max-height:1em; max-width:1em;", class:"logo-image seoHide", "ng-style":"{'display':'initial'}"
                            %span 
                                CJ's Mobile DJ
                .col-sm-3.text-right
                    %div.h2.hidden-sm.hidden-xs <i class="material-icons seoHide" ng-style="{'display':'initial'}">place</i> Boise, Idaho
                .col-sm-3.col-xs-12
                    %a.bttn.open-bttn.nav-bttn.seoHide{'ng-click':'wc.toggleProp("action"); ac.sendEventData("cta-btn-0", "click", wc.action)', "ng-show":"!wc.action", "ng-style":"{'display':'initial'}"} GET A QUOTE
                    %a.bttn.open-bttn.nav-bttn.seoHide{'ng-click':'wc.toggleProp("action");', "ng-show":"wc.action", "ng-style":"{'display':'initial'}" } EXIT
                .col-md-1.col-xs-0

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
// %p{id:"notice"}= notice 
=render 'nav'
-(0..5).each do |a|
  %br
.container-fluid
  .row
    -@posts.each do |post|
      .col-xs-12.col-md-3
        .h3= post.title
        .h3
          %small= post.subtitle
        %p= post.author
        %p.fr-view!=post.body.truncate_words(28)
        = link_to 'Show', post_path(post)
        = link_to 'Edit', edit_post_path(post)
        = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form'

= link_to 'Back', posts_path
= javascript_include_tag 'posts', 'data-turbolinks-track' => true 

app/views/posts/show.html.haml
<link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
.container-fluid
  .row
    .banner
      =image_tag "https://hd.unsplash.com/photo-1468971050039-be99497410af", class:"banner-image"
    .col-xs-12.col-md-8.col-md-offset-2
      %p{id:"notice"}=notice
      %h1= @post.title
      .h2= @post.subtitle
      %p!="by <em>#{@post.author}</em>"
      %p.fr-view!= @post.body
      =link_to 'Edit', edit_post_path(@post)
      =link_to 'Back', posts_path

app/views/static_pages/_popover.html.haml
.pop-over-container.seoHide{'ng-show':'wc.action', style:"display:none;", "ng-style":"{'display':'flex'}" }
    .action-box
        %a{href:"tel:1-208-407-0301", "ng-show":"wc.isMobile"}
            %button.btn-action
                // Phone
                <i class="material-icons">&#xE0CD;</i>
                Call
        %a{href:"{{wc.smsLink}}", "ng-show":"wc.isMobile"}
            %button.btn-action
                // Text
                <i class="material-icons">&#xE0D8;</i>
                Text
        %button.btn-action{"ng-click":"wc.phoneNumToggle()", "ng-show":"!wc.phoneNum && !wc.isMobile"}
            <i class="h1 material-icons">&#xE0CD;</i>
            Call
        %button.btn-action{"ng-click":"wc.phoneNumToggle()", "ng-show":"!wc.phoneNum && !wc.isMobile"}
            <i class="material-icons">&#xE0D8;</i>
            Text
        .h4{"ng-show":"wc.phoneNum"}
            %input.phone-input{value:"1-208-407-0301"}
        %a{href:"/form", target:"_blank"}
            %button.btn-action{'ng-click':''}
                // Description
                <i class="material-icons">&#xE873;</i>
                Form

app/views/static_pages/wedding-partials/_nav.html.haml
.row.background-5.bg
  .dark-row
    .container-fluid
      .row.nav-row
        .col-sm-1.col-xs-0
        .col-sm-5.col-xs-12.text-left
          %a{href:"#{root_path}", "@click":"wc.action=false"}
            .h1 
              =image_tag "heart-logo-square.svg", fill:'pink', style:"max-height:1em; max-width:1em;", class:"logo-image seoHide", "v-style":"{'display':'initial'}"
              %span 
                CJ's Mobile DJ
        .col-sm-3.text-right
          %div.h2{"v-show":"!wc.isMobile"} <i class="material-icons seoHide" v-style="display:initial;">place</i> Boise, Idaho
        .col-sm-3.col-xs-12
          %a.bttn.open-bttn.nav-bttn.seoHide{'@click':'wc.toggleProp("action"); sendEventData("cta-btn-0", "click", wc.action)', "v-show":"!wc.action", "v-style":"{'display':'initial'}"} GET A QUOTE
          %a.bttn.open-bttn.nav-bttn.seoHide{'@click':'wc.toggleProp("action");', "v-show":"wc.action", "v-style":"{'display':'initial'}" } EXIT
        .col-md-1.col-xs-0
    .col-xs-0.col-md-2
    .col-xs-12.col-md-8
      .flex-area
        .h2.real-text.animated.fadeIn The soundtrack to your happily ever after
        .text-area-wrap
          -# %span.text-area.text-area-main#text-area
        %a.bttn.open-bttn.animated.fadeIn.cta-bttn{'@click':'wc.toggleProp("action"); sendEventData("cta-btn-1", "click")', style:"margin-bottom:-15%"} LET'S DANCE!
    .col-xs-12.col-md-2

app/views/static_pages/weddings.html.haml
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">

.container-fluid{'ng-controller':'WeddingsController as wc'}
	.row.background-5.bg
		.dark-row
			.container-fluid
				.row.nav-row
					.col-sm-1.col-xs-0
					.col-sm-5.col-xs-12.text-left
						%a{href:"#{root_path}", "ng-click":"wc.action=false"}
							.h1 
								=image_tag "heart-logo-square.svg", fill:'pink', style:"max-height:1em; max-width:1em;", class:"logo-image seoHide", "ng-style":"{'display':'initial'}"
								%span 
									CJ's Mobile DJ
					.col-sm-3.text-right
						%div.h2.hidden-xs.hidden-sm <i class="material-icons seoHide" style="display:initial;">place</i> Boise, Idaho
					.col-sm-3.col-xs-12
						%a.bttn.open-bttn.nav-bttn.seoHide{'ng-click':'wc.toggleProp("action"); ac.sendEventData("cta-btn-0", "click", wc.action)', "ng-show":"!wc.action", "ng-style":"{'display':'initial'}"} GET A QUOTE
						%a.bttn.open-bttn.nav-bttn.seoHide{'ng-click':'wc.toggleProp("action");', "ng-show":"wc.action", "ng-style":"{'display':'initial'}" } EXIT
					.col-md-1.col-xs-0
			.col-xs-0.col-md-2
			.col-xs-12.col-md-8
				.flex-area
					.h2.real-text.animated.fadeIn The soundtrack to your happily ever after
					.text-area-wrap
						-# %span.text-area.text-area-main#text-area
					%a.bttn.open-bttn.animated.fadeIn.cta-bttn{'ng-click':'wc.toggleProp("action"); ac.sendEventData("cta-btn-1", "click")', style:"margin-bottom:-15%"} LET'S DANCE!
			.col-xs-12.col-md-2
	.row.background-3.text-section-container.bg
		.h3
			Your Checklist Just Got Shorter
			%i.fa.fa-check
			%br
		.second-row
			.col-xs-12.col-md-10.col-md-offset-1
				.row
					.col-xs-12.col-md-3
						-# =image_tag 'perfect-fit.svg', class:'action-icon'
						.h3 We listen.
					.col-xs-12.col-md-3
						-# =image_tag 'speaker.svg', class:'action-icon'
						.h3 We prep it.
					.col-xs-12.col-md-3
						-# =image_tag 'mic.svg', class:'action-icon'
						.h3 We do it.
					.col-xs-12.col-md-3
						-# =image_tag 'mic.svg', class:'action-icon'
						.h3 You dance.
				.row
					.col-md-4.col-md-offset-4
						%a
							.bttn.open-bttn.animated.fadeIn.cta-bttn.in-block-cta-btn{'ng-click':'wc.toggleProp("action"); ac.sendEventData("cta-btn-2", "click")'}  SIGN ME UP!
		.row.second-row
	.row.background-7.text-section-container.bg
		.second-row.dark-row.content-container
			.col-md-4.col-md-offset-4
				.nested-text
					-# .h3 
					.h3.text-left We bring the music.
					.h3.text-left You bring the party.
			.col-xs-0.col-md-7
	.row.background-3.text-section-container
		.row.second-row
			.col-xs-12.col-md-10.col-md-offset-1
				-# =image_tag 'speaker.svg', class:'action-icon'
				.h3 You've waited your entire life for this day.
				.h3 Don't leave your wedding's entertainment to chance.
				-# =image_tag 'mic.svg', class:'action-icon'
				%br
				%br
				%a.bttn.open-bttn.animated.fadeIn.cta-bttn.in-block-cta-btn{'ng-click':'wc.toggleProp("action"); ac.sendEventData("cta-btn-3", "click")'}  LEAVE IT TO US
	.row
		.background-8.text-section-container.bg
			.dark-row.flex-col.space-around
				.col-xs-12.col-md-10.col-md-offset-1
					.col-xs-12.col-md-4
						-# =image_tag 'speaker.svg', class:'action-icon'
						.h1
							%i.fa.fa-smile-o.fa-lg
						.stat-item
							%span 3,457
						.stat-item
							%span Total Smiles
					.col-xs-12.col-md-4
						-# =image_tag 'speaker.svg', class:'action-icon'
						.h1
							%i.fa.fa-child.fa-lg
						.stat-item
							%span 238
						.stat-item
							%span Bad Dance Moves
					.col-xs-12.col-md-4
						-# =image_tag 'speaker.svg', class:'action-icon'
						.h1
							%i.fa.fa-heartbeat.fa-lg
						.stat-item
							%span 87
						.stat-item
							%span LOL Memories
	.row.background-3.text-section-container
		.col-xs-12.col-md-10.col-md-offset-1
			.h2.bold How it works
			%br
			.col-md-9.col-md-offset-2
				%ol
					%li Tell us your vision
					%li We'll create a plan to make it happen
					%li Create a lifetime of memories in one night
					%br
					%br
			%br
			%br
			%br
			.reviews-container
				<script src='//www.weddingwire.com/assets/vendor/widgets/my-reviews.js' type='application/javascript'></script>
				<div class='ww-reset ww-reviews-widget' id='ww-widget-reviews'>
				<div class='ww-reviews-placeholder'>
				Read all of our wedding reviews on our
				<a target="_blank" href="https://www.weddingwire.com/biz/cjs-mobile-dj-and-entertainment-boise/9697673b2816da69.html">CJ&#39;s Mobile DJ and Entertainment</a>
				Storefront at
				<a alt="WeddingWire" href="https://www.weddingwire.com"><img src="//www.weddingwire.com/assets/widgets/logo/WWlogo-83x19.gif" alt="Wwlogo 83x19" />
				</a></div>
				</div>
				<script>
				  WeddingWire.createReview({"vendorId":"9697673b2816da69", "id":"ww-widget-reviews" });
				</script>
				<style>
				\.ww-reviews-widget {
				border:none;
				min-width: 165px;
				max-width: 700px;
				box-shadow: 2px 2px 20px rgba(0,0,0,0.2);
				overflow: hidden;
				}
				</style>
	.row.second-row.row.footer.background-last
		.col-md-6.col-md-offset-3.footer-col
			=image_tag "record.svg", class:"footer-image" 
			%div
				%a.bttn.open-bttn{'ng-click':'wc.toggleProp("action"); ac.sendEventData("cta-btn-footer", "click")'}  GET A QUOTE 
			%address
				%span Boise, ID
				%span.accent /
				%span Serving the Pacific Northwest
			.info-group
				%p.inline
				%a{href:"tel:1-208-407-0301"}208.407.0301
				%span.accent /
				%a.accent{href:"mailto:clancy@cjyourdj.com"} Clancy@CJYourDJ.com
				%div ©  CJ's Mobile DJ 2016
				%a{href:"https:/\/www.google.com/maps/place/CJ's+Mobile+DJ+and+Entertainment+Services/@43.599088,-116.222002,15z/data=!4m5!3m4!1s0x0:0x26e4edf3fdb13d1d!8m2!3d43.599088!4d-116.222002", target:"_blank"}
			%div
				%i.fa.fa-google.fa-3x
				%span &nbsp; &nbsp; &nbsp; &nbsp;
				%a{href:"https://www.facebook.com/cjsmobiledj/", target:"_blank"}
					%i.fa.fa-facebook.fa-3x
				%div{style:"opacity:0.3"}
					-if user_signed_in?
						=link_to 'Admin', admin_path 
						|
						=link_to('Log Out', destroy_user_session_path, :method => :delete)
					-else
						= link_to 'Login', new_user_session_path
	.nav-row-solid.nav-row-close
		%a.bttn.nav-bttn.close-bttn{style:"display:block;z-index:9999999999"} EXIT FORM
				
				
	=render 'popover'
					
					
					
					
					
					
				










				
				
	/ <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
	/ <defs>
	/ <filter id="glitch" x="0" y="0">
	/ <feColorMatrix in="SourceGraphic" mode="matrix" values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0" result="r" />
	/
	/ <feOffset in="r" result="r" dx="-5">
	/ <animate attributeName="dx" attributeType="XML" values="0; -5; 0; -18; -2; -4; 0 ;-3; 0" dur="0.2s" repeatCount="indefinite"/>
	/ </feOffset>
	/ <feColorMatrix in="SourceGraphic" mode="matrix" values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0" result="g"/>
	/ <feOffset in="g" result="g" dx="-5" dy="1">
	/ <animate attributeName="dx" attributeType="XML" values="0; 0; 0; -3; 0; 8; 0 ;-1; 0" dur="0.15s" repeatCount="indefinite"/>
	/ </feOffset>
	/ <feColorMatrix in="SourceGraphic" mode="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0" result="b"/>
	/ <feOffset in="b" result="b" dx="5" dy="2">
	/ <animate attributeName="dx" attributeType="XML" values="0; 3; -1; 4; 0; 2; 0 ;18; 0" dur="0.35s" repeatCount="indefinite"/>
	/ </feOffset>
	/ <feBlend in="r" in2="g" mode="screen" result="blend" />
	/ <feBlend in="blend" in2="b" mode="screen" result="blend" />
	/ </filter>
	/ </defs>
	/ </svg>

			
			
				
					
					
					
					
					
					
					
					
					
					
					
					
				
				
				
				
				
				
				
				
				
				
				
			
			
			
			
			
			
/ <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
/ <defs>
/ <filter id="glitch" x="0" y="0">
/ <feColorMatrix in="SourceGraphic" mode="matrix" values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0" result="r" />
/
/ <feOffset in="r" result="r" dx="-5">
/ <animate attributeName="dx" attributeType="XML" values="0; -5; 0; -18; -2; -4; 0 ;-3; 0" dur="0.2s" repeatCount="indefinite"/>
/ </feOffset>
/ <feColorMatrix in="SourceGraphic" mode="matrix" values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0" result="g"/>
/ <feOffset in="g" result="g" dx="-5" dy="1">
/ <animate attributeName="dx" attributeType="XML" values="0; 0; 0; -3; 0; 8; 0 ;-1; 0" dur="0.15s" repeatCount="indefinite"/>
/ </feOffset>
/ <feColorMatrix in="SourceGraphic" mode="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0" result="b"/>
/ <feOffset in="b" result="b" dx="5" dy="2">
/ <animate attributeName="dx" attributeType="XML" values="0; 3; -1; 4; 0; 2; 0 ;18; 0" dur="0.35s" repeatCount="indefinite"/>
/ </feOffset>
/ <feBlend in="r" in2="g" mode="screen" result="blend" />
/ <feBlend in="blend" in2="b" mode="screen" result="blend" />
/ </filter>
/ </defs>
/ </svg>